### ISSUE TITLE
W11 - Relatórios

### ISSUE THREAD

**Issue by hyperiondeimos** [hyperiondeimos/PCCT2018#10]
A partir dessa semana, TODOS os relatórios deveram ser entregues por aqui. Irei criar uma lista de entrega e bloquear o acesso a esse ISSUE durante a semana.

Essa semana é a W11 do ano:

Entregas:

- [x] Amarilda
- [ ] Isabelle
- [ ] Julia
- [x] Marcos Vinicius
- [x] Matheus
- [x] Rafaela
- [x] Sarah

Prazo máximo de entrega: 24/03/2018, as 18h.

**Comment by MViniciusSC** [comment]
[Modelo de Relatório Semanal PCCT.pdf](https://github.com/hyperiondeimos/PCCT2018/files/1843935/Modelo.de.Relatorio.Semanal.PCCT.pdf)

**Comment by hyperiondeimos** [comment]
Esse em especial sou eu que fecho, ok?

**Comment by SarahEven** [comment]
W11Modelo.de.Relatorio.Semanal.PCCT.

**Comment by amarildacruz** [comment]
[relatório da semana.pdf](https://github.com/hyperiondeimos/PCCT2018/files/1844731/relatorio.da.semana.pdf)
_

**Comment by hyperiondeimos** [comment]
Sarah, seu report não foi enviado. Reenviar.

**Comment by matheusalucard53** [comment]
[Relatório Semanal PCCT- semana 11.docx](https://github.com/hyperiondeimos/PCCT2018/files/1844753/Relatorio.Semanal.PCCT-.semana.11.docx)
