### ISSUE TITLE
W12 - Report Semanal

### ISSUE THREAD

**Issue by hyperiondeimos** [hyperiondeimos/PCCT2018#13]
Issue da entrega do report semanal da semana 12 (W12).

Entregas Confirmadas:

- [ ] Amarilda
- [ ] Isabelle
- [ ] Julia
- [x] Marcos Vinicius
- [ ] Matheus
- [ ] Rafaela
- [ ] Sarah

Prazo máximo de entrega: 31/03/2018, as 18h.

**Comment by matheusalucard53** [comment]
[Relatório Semanal PCCT- semana 12.docx](https://github.com/hyperiondeimos/PCCT2018/files/1865873/Relatorio.Semanal.PCCT-.semana.12.docx)
